# EXPERIMENT 3

In [1]:
import numpy as np
import pandas as pd
data_set=pd.read_excel(r'CC:\clg\4 DPFE MEENAKSHI\OneDrive\Desktop\billionaires.xlsx')

In [2]:
data_set.fillna(value=100)

,name,rank,year,company.founded,company.name,company.relationship,company.sector,company.type,demographics.age,demographics.gender,...,location.gdp,location.region,wealth.type,wealth.worth in billions,wealth.how.category,wealth.how.from emerging,wealth.how.industry,wealth.how.inherited,wealth.how.was founder,wealth.how.was political
0,Bill Gates,1,1996,1975,Microsoft,founder,Software,new,40,male,...,8100000000000,North America,founder non-finance,18.5,New Sectors,True,Technology-Computer,not inherited,True,True
1,Bill Gates,1,2001,1975,Microsoft,founder,Software,new,45,male,...,10600000000000,North America,founder non-finance,58.7,New Sectors,True,Technology-Computer,not inherited,True,True
2,Bill Gates,1,2014,1975,Microsoft,founder,Software,new,58,male,...,0,North America,founder non-finance,76.0,New Sectors,True,Technology-Computer,not inherited,True,True
3,Warren Buffett,2,1996,1962,Berkshire Hathaway,founder,Finance,new,65,male,...,8100000000000,North America,founder non-finance,15.0,Traded Sectors,True,Consumer,not inherited,True,True
4,Warren Buffett,2,2001,1962,Berkshire Hathaway,founder,Finance,new,70,male,...,10600000000000,North America,founder non-finance,32.3,Traded Sectors,True,Consumer,not inherited,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2609,Wu Chung-Yi,1565,2014,1991,Tingyi,investor,beverages and food,new,55,male,...,0,East Asia,executive,1.0,Traded Sectors,True,Non-consumer industrial,not inherited,True,True
2610,Wu Xiong,1565,2014,1999,Biostime International Holdings,owner,infant formula,new,0,male,...,0,East Asia,executive,1.0,Traded Sectors,True,Consumer,not inherited,True,True
2611,Yang Keng,1565,2014,0,Blue Ray Corp,chairman,real estate,new,53,male,...,0,East Asia,self-made finance,1.0,Financial,True,Real Estate,not inherited,True,True
2612,Zdenek Bakala,1565,2014,1994,Patria Finance,founder,coal,new,53,male,...,0,Europe,privatized and resources,1.0,Resource Related,True,Mining and metals,not inherited,True,True
2613,Zhu Wenchen,1565,2014,1999,Furen Pharmaceutical Group,chairman,pharmaceuticals,new,48,male,...,0,East Asia,executive,1.0,New Sectors,True,Technology-Medical,not inherited,True,True

In [3]:
data_set['year'].fillna(value=2000)

0       1996
1       2001
2       2014
3       1996
4       2001
        ...
2609    2014
2610    2014
2611    2014
2612    2014
2613    2014
Name: year, Length: 2614, dtype: int64

In [4]:
m=data_set['year'].mode()

In [5]:
m

0    2014
Name: year, dtype: int64

In [6]:
data_set.fillna(value=m[0])#setting  mean as missing value

,name,rank,year,company.founded,company.name,company.relationship,company.sector,company.type,demographics.age,demographics.gender,...,location.gdp,location.region,wealth.type,wealth.worth in billions,wealth.how.category,wealth.how.from emerging,wealth.how.industry,wealth.how.inherited,wealth.how.was founder,wealth.how.was political
0,Bill Gates,1,1996,1975,Microsoft,founder,Software,new,40,male,...,8100000000000,North America,founder non-finance,18.5,New Sectors,True,Technology-Computer,not inherited,True,True
1,Bill Gates,1,2001,1975,Microsoft,founder,Software,new,45,male,...,10600000000000,North America,founder non-finance,58.7,New Sectors,True,Technology-Computer,not inherited,True,True
2,Bill Gates,1,2014,1975,Microsoft,founder,Software,new,58,male,...,0,North America,founder non-finance,76.0,New Sectors,True,Technology-Computer,not inherited,True,True
3,Warren Buffett,2,1996,1962,Berkshire Hathaway,founder,Finance,new,65,male,...,8100000000000,North America,founder non-finance,15.0,Traded Sectors,True,Consumer,not inherited,True,True
4,Warren Buffett,2,2001,1962,Berkshire Hathaway,founder,Finance,new,70,male,...,10600000000000,North America,founder non-finance,32.3,Traded Sectors,True,Consumer,not inherited,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2609,Wu Chung-Yi,1565,2014,1991,Tingyi,investor,beverages and food,new,55,male,...,0,East Asia,executive,1.0,Traded Sectors,True,Non-consumer industrial,not inherited,True,True
2610,Wu Xiong,1565,2014,1999,Biostime International Holdings,owner,infant formula,new,0,male,...,0,East Asia,executive,1.0,Traded Sectors,True,Consumer,not inherited,True,True
2611,Yang Keng,1565,2014,0,Blue Ray Corp,chairman,real estate,new,53,male,...,0,East Asia,self-made finance,1.0,Financial,True,Real Estate,not inherited,True,True
2612,Zdenek Bakala,1565,2014,1994,Patria Finance,founder,coal,new,53,male,...,0,Europe,privatized and resources,1.0,Resource Related,True,Mining and metals,not inherited,True,True
2613,Zhu Wenchen,1565,2014,1999,Furen Pharmaceutical Group,chairman,pharmaceuticals,new,48,male,...,0,East Asia,executive,1.0,New Sectors,True,Technology-Medical,not inherited,True,True

In [7]:
data_set.drop([2,5,7])

,name,rank,year,company.founded,company.name,company.relationship,company.sector,company.type,demographics.age,demographics.gender,...,location.gdp,location.region,wealth.type,wealth.worth in billions,wealth.how.category,wealth.how.from emerging,wealth.how.industry,wealth.how.inherited,wealth.how.was founder,wealth.how.was political
0,Bill Gates,1,1996,1975,Microsoft,founder,Software,new,40,male,...,8100000000000,North America,founder non-finance,18.5,New Sectors,True,Technology-Computer,not inherited,True,True
1,Bill Gates,1,2001,1975,Microsoft,founder,Software,new,45,male,...,10600000000000,North America,founder non-finance,58.7,New Sectors,True,Technology-Computer,not inherited,True,True
3,Warren Buffett,2,1996,1962,Berkshire Hathaway,founder,Finance,new,65,male,...,8100000000000,North America,founder non-finance,15.0,Traded Sectors,True,Consumer,not inherited,True,True
4,Warren Buffett,2,2001,1962,Berkshire Hathaway,founder,Finance,new,70,male,...,10600000000000,North America,founder non-finance,32.3,Traded Sectors,True,Consumer,not inherited,True,True
6,Oeri Hoffman and Sacher,3,1996,1896,F. Hoffmann-La Roche,NaN,pharmaceuticals,new,0,NaN,...,330000000000,Europe,inherited,13.1,New Sectors,True,Technology-Medical,3rd generation,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2609,Wu Chung-Yi,1565,2014,1991,Tingyi,investor,beverages and food,new,55,male,...,0,East Asia,executive,1.0,Traded Sectors,True,Non-consumer industrial,not inherited,True,True
2610,Wu Xiong,1565,2014,1999,Biostime International Holdings,owner,infant formula,new,0,male,...,0,East Asia,executive,1.0,Traded Sectors,True,Consumer,not inherited,True,True
2611,Yang Keng,1565,2014,0,Blue Ray Corp,chairman,real estate,new,53,male,...,0,East Asia,self-made finance,1.0,Financial,True,Real Estate,not inherited,True,True
2612,Zdenek Bakala,1565,2014,1994,Patria Finance,founder,coal,new,53,male,...,0,Europe,privatized and resources,1.0,Resource Related,True,Mining and metals,not inherited,True,True
2613,Zhu Wenchen,1565,2014,1999,Furen Pharmaceutical Group,chairman,pharmaceuticals,new,48,male,...,0,East Asia,executive,1.0,New Sectors,True,Technology-Medical,not inherited,True,True

In [8]:
data_set.drop(['rank','year'],axis=1)

,name,company.founded,company.name,company.relationship,company.sector,company.type,demographics.age,demographics.gender,location.citizenship,location.country code,location.gdp,location.region,wealth.type,wealth.worth in billions,wealth.how.category,wealth.how.from emerging,wealth.how.industry,wealth.how.inherited,wealth.how.was founder,wealth.how.was political
0,Bill Gates,1975,Microsoft,founder,Software,new,40,male,United States,USA,8100000000000,North America,founder non-finance,18.5,New Sectors,True,Technology-Computer,not inherited,True,True
1,Bill Gates,1975,Microsoft,founder,Software,new,45,male,United States,USA,10600000000000,North America,founder non-finance,58.7,New Sectors,True,Technology-Computer,not inherited,True,True
2,Bill Gates,1975,Microsoft,founder,Software,new,58,male,United States,USA,0,North America,founder non-finance,76.0,New Sectors,True,Technology-Computer,not inherited,True,True
3,Warren Buffett,1962,Berkshire Hathaway,founder,Finance,new,65,male,United States,USA,8100000000000,North America,founder non-finance,15.0,Traded Sectors,True,Consumer,not inherited,True,True
4,Warren Buffett,1962,Berkshire Hathaway,founder,Finance,new,70,male,United States,USA,10600000000000,North America,founder non-finance,32.3,Traded Sectors,True,Consumer,not inherited,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2609,Wu Chung-Yi,1991,Tingyi,investor,beverages and food,new,55,male,Taiwan,Taiwan,0,East Asia,executive,1.0,Traded Sectors,True,Non-consumer industrial,not inherited,True,True
2610,Wu Xiong,1999,Biostime International Holdings,owner,infant formula,new,0,male,China,CHN,0,East Asia,executive,1.0,Traded Sectors,True,Consumer,not inherited,True,True
2611,Yang Keng,0,Blue Ray Corp,chairman,real estate,new,53,male,China,CHN,0,East Asia,self-made finance,1.0,Financial,True,Real Estate,not inherited,True,True
2612,Zdenek Bakala,1994,Patria Finance,founder,coal,new,53,male,Czech Republic,CZE,0,Europe,privatized and resources,1.0,Resource Related,True,Mining and metals,not inherited,True,True
2613,Zhu Wenchen,1999,Furen Pharmaceutical Group,chairman,pharmaceuticals,new,48,male,China,CHN,0,East Asia,executive,1.0,New Sectors,True,Technology-Medical,not inherited,True,True

In [9]:
m=data_set['name'].mode()

In [10]:
m

0                 Abigail Johnson
1         Abilio dos Santos Diniz
2                      Akira Mori
3                Alain Wertheimer
4      Alberto Bailleres Gonzalez
                  ...
129            Thaksin Shinawatra
130            Thomas Schmidheiny
131               Tiong Hiew King
132                Warren Buffett
133                   Wee Cho Yaw
Name: name, Length: 134, dtype: object

In [11]:
data_set['name'].fillna(m)

0           Bill Gates
1           Bill Gates
2           Bill Gates
3       Warren Buffett
4       Warren Buffett
             ...
2609       Wu Chung-Yi
2610          Wu Xiong
2611         Yang Keng
2612     Zdenek Bakala
2613       Zhu Wenchen
Name: name, Length: 2614, dtype: object

In [12]:
data_set

,name,rank,year,company.founded,company.name,company.relationship,company.sector,company.type,demographics.age,demographics.gender,...,location.gdp,location.region,wealth.type,wealth.worth in billions,wealth.how.category,wealth.how.from emerging,wealth.how.industry,wealth.how.inherited,wealth.how.was founder,wealth.how.was political
0,Bill Gates,1,1996,1975,Microsoft,founder,Software,new,40,male,...,8100000000000,North America,founder non-finance,18.5,New Sectors,True,Technology-Computer,not inherited,True,True
1,Bill Gates,1,2001,1975,Microsoft,founder,Software,new,45,male,...,10600000000000,North America,founder non-finance,58.7,New Sectors,True,Technology-Computer,not inherited,True,True
2,Bill Gates,1,2014,1975,Microsoft,founder,Software,new,58,male,...,0,North America,founder non-finance,76.0,New Sectors,True,Technology-Computer,not inherited,True,True
3,Warren Buffett,2,1996,1962,Berkshire Hathaway,founder,Finance,new,65,male,...,8100000000000,North America,founder non-finance,15.0,Traded Sectors,True,Consumer,not inherited,True,True
4,Warren Buffett,2,2001,1962,Berkshire Hathaway,founder,Finance,new,70,male,...,10600000000000,North America,founder non-finance,32.3,Traded Sectors,True,Consumer,not inherited,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2609,Wu Chung-Yi,1565,2014,1991,Tingyi,investor,beverages and food,new,55,male,...,0,East Asia,executive,1.0,Traded Sectors,True,Non-consumer industrial,not inherited,True,True
2610,Wu Xiong,1565,2014,1999,Biostime International Holdings,owner,infant formula,new,0,male,...,0,East Asia,executive,1.0,Traded Sectors,True,Consumer,not inherited,True,True
2611,Yang Keng,1565,2014,0,Blue Ray Corp,chairman,real estate,new,53,male,...,0,East Asia,self-made finance,1.0,Financial,True,Real Estate,not inherited,True,True
2612,Zdenek Bakala,1565,2014,1994,Patria Finance,founder,coal,new,53,male,...,0,Europe,privatized and resources,1.0,Resource Related,True,Mining and metals,not inherited,True,True
2613,Zhu Wenchen,1565,2014,1999,Furen Pharmaceutical Group,chairman,pharmaceuticals,new,48,male,...,0,East Asia,executive,1.0,New Sectors,True,Technology-Medical,not inherited,True,True